name: Ouchat-Electronics CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Build with ESP‑IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0
          target: "esp32s3"
          path: "."